language: python
sudo: required
dist: xenial
before_install:
- chmod +x .build/.travis/*.sh
matrix:
  include:
  - env: IMG="ubuntu1604" BUILD_TARGET="pex" UST_BUILD_EXE=0 UST_EXTENSION=1 UST_SHELL_EXEC=1
    python:
    - 3.6
    install:
    - ".build/.travis/install-ubuntu.sh"
    script:
    - ".build/.travis/build-py36.sh"
    - ".build/.travis/release.sh"
    - python setup.py test
  - env: IMG="ubuntu1604" BUILD_TARGET="standalone" UST_BUILD_EXE=1 UST_EXTENSION=0
      UST_SHELL_EXEC=0
    python:
    - 3.6
    install:
    - ".build/.travis/install-ubuntu.sh"
    script:
    - ".build/.travis/build-py36.sh"
    - ".build/.travis/release.sh"
    - python setup.py test
  - env: IMG="ubuntu1604" BUILD_TARGET="pex" UST_BUILD_EXE=0 UST_EXTENSION=1 UST_SHELL_EXEC=1
    python:
    - 2.7
    install:
    - ".build/.travis/install-ubuntu.sh"
    script:
    - ".build/.travis/build-py27.sh"
    - ".build/.travis/release.sh"
    - python setup.py test
  - env: OS="centos:7" IMG="centos7" SH="docker exec -t ${IMG} bash -c" BUILD_TARGET="pex"
    services:
    - docker
    python:
    - 3.6
    before_install:
    - chmod +x .build/.travis/*.sh
    - docker run -d --name ${IMG} -v $(pwd):/travis -w /travis -e IMG="${IMG}" -e
      TRAVIS_TAG="${TRAVIS_TAG}" -e BUILD_TARGET="${BUILD_TARGET}" -e UST_BUILD_EXE=0
      -e UST_EXTENSION=1 -e UST_SHELL_EXEC=1 ${OS} tail -f /dev/null
    - docker ps
    install:
    - "$SH .build/.travis/install-centos.sh"
    script:
    - "$SH .build/.travis/build-py36-centos.sh"
  - env: OS="centos:7" IMG="centos7" SH="docker exec -t ${IMG} bash -c" BUILD_TARGET="standalone"
    services:
    - docker
    python:
    - 3.6
    before_install:
    - chmod +x .build/.travis/*.sh
    - docker run -d --name ${IMG} -v $(pwd):/travis -w /travis -e IMG="${IMG}" -e
      TRAVIS_TAG="${TRAVIS_TAG}" -e BUILD_TARGET="${BUILD_TARGET}" -e UST_BUILD_EXE=1
      -e UST_EXTENSION=0 -e UST_SHELL_EXEC=0 ${OS} tail -f /dev/null
    - docker ps
    install:
    - "$SH .build/.travis/install-centos.sh"
    script:
    - "$SH .build/.travis/build-py36-centos.sh"
  - env: OS="centos:7" IMG="centos7" SH="docker exec -t ${IMG} bash -c" BUILD_TARGET="pex"
    services:
    - docker
    python:
    - 2.7
    before_install:
    - chmod +x .build/.travis/*.sh
    - docker run -d --name ${IMG} -v $(pwd):/travis -w /travis -e IMG="${IMG}" -e
      TRAVIS_TAG="${TRAVIS_TAG}" -e BUILD_TARGET="${BUILD_TARGET}" -e UST_BUILD_EXE=0
      -e UST_EXTENSION=1 -e UST_SHELL_EXEC=1 ${OS} tail -f /dev/null
    - docker ps
    install:
    - "$SH .build/.travis/install-centos.sh"
    script:
    - "$SH .build/.travis/build-py27.sh"
    - "$SH .build/.travis/release.sh"
    - $SH "python setup.py test"
deploy:
  provider: releases
  api_key:
    secure: ZZPQGIE6kJD7qDnlW53x8Pytw9b0+zA2xeyl6cL29P6EmoFJwZSd84SOu3BW9XkxGQSxjMJ6ejpry3TFODgxF2tIkXT52xgmw0ZzuGkbLmqYlIpjFEgqxIFg5oGtBQV3PDPveN9kWBcRLPR/FvdkEzokWsqtSupwkTmZamz7qOM47xyc4hfPdir+jBa9jGRX7dhQhm2LBd7wqgOHkJYKukEf2tjF4R4+AS8WkZUrPQH/M7BZ3vwb2hIWLQ08SeML1giouvg0l4dkiA2FZZkvAo9iPebDdfPP015ssvwoR4jdIwl5VfALzEoT0cQCG8jxGasOHC9GUyaTFMFWDA8pPR3eGbJ1ogDG4uGTssVuSLQN2OK2io1UoOC+tKG7/zidKBO2PSLd9YbqIksWdvukKMdPeYUEtZRj58oTUs8ZmjWmCFPhm31sq6hgbiGFwlFCfHF+Hms3JUtIU51r28xy6bjkdWlcJxDPKAuYn1W+S48CU3S1+Is/FLCr6XaSpE2H1ly3oZhod4GqZVKKFKKYPHm1xa5YPCPZc6bj9/XTGXNwgznEGfJRUPmmVQio9CDx9uafTFy9NV40lvP0jssPQp1w2pkl+gAUrQLhmrq4huzPhFvK8id1O1Vod/gsbrDlrxfeJ3lVihjNJ5Buryig47mTICIrEfmXXkGd/6vnFB0=
  file_glob: true
  file: release/*.gz
  skip_cleanup: true
  draft: true
  on:
    tags: true
    repo: sdhau/user-sync.py
    branch: build/exe
