language: python
sudo: required
dist: xenial
before_install:
- chmod +x .build/.travis/*.sh
matrix:
  include:
  - env:
    - IMG="ubuntu1604"
    - BUILD_TARGET="pex"
    - UST_BUILD_EXE=0
    - UST_EXTENSION=1
    - UST_SHELL_EXEC=1
    python:
    - 3.6
    install:
    - ".build/.travis/install-ubuntu.sh"
    script:
    - ".build/.travis/build-py36.sh"
    - ".build/.travis/release.sh"
    - python setup.py test
  - env:
    - IMG="ubuntu1604"
    - BUILD_TARGET="standalone"
    - UST_BUILD_EXE=1
    - UST_EXTENSION=0
    - UST_SHELL_EXEC=0
    python:
    - 3.6
    install:
    - ".build/.travis/install-ubuntu.sh"
    script:
    - ".build/.travis/build-py36.sh"
    - ".build/.travis/release.sh"
    - python setup.py test
deploy:
  provider: releases
  api_key:
    secure: jTAMZg78nOowefYN3nIX/3DTjmY95oIFIWJMgpUw6GUyBsr7mBtPfHqUhlhid1ORwpNO2NzIdzQpMDMUXtIcO7xRWnO+AkIkHHsDwBa7R1TP5Ary8DjKLzgwgBH/0sy7yQtWUi65wCG0mZWWY7HicwKmm5eRPdnt8TYVNGBJ03slpFITyvKkdR6UWiOSN9QZ4pRDZLooYDxE0HIYsHVnLFhrYZ0dqlqIfIo8JmouOfc0VYUXZ3FtDtGx5J1IGqumrDfJc5LDQJdvWXiDJrdjYggwJVx5E2sDSsgOu7K1bAw950fw3kxt88WIHRs7iNZTrnoIS2dw0ZQOwgSwWLJVSadqglEb6xwO3SUo3ppN6YRyTGJh+HSLEjp4Ek3B1yPGst26P5dJ/JpSGR4QoOP6GzyRPYutKRrKRLD6Qj3Oh79VpGelRO1yXMeCjSfAL5jVa7tKjhgXn5ENFFoljH+Df0Wu0omVOThDdCWybi72Vx+UswqqY7XeXLf/swYZRmR5+wH+wmjtyvyMlSabVEWAlPMdsnLO3kcJjHjZhuUd8BjvqRFcwfsPVHZfNUKorWMm+O7K41Z34Ok84rtKAgqnnL+wtpp2tdnVYroafAlBY1xK93DkW6jGd2kUZyuN6Fpv1tK4nOXZzIAQ5gYYlIcYKvaOL6aH8bw8BJLnOFaFCp8=
  file_glob: true
  skip_cleanup: true
  draft: true
  file: release/*.gz
  on:
    repo: sdhau/user-sync.py
    all_branches: true
    tags: true

