language: python
sudo: required
dist: xenial
before_install:
- chmod +x .build/.travis/*.sh
matrix:
  include:
  - env: IMG="ubuntu1604" BUILD_TARGET="pex" UST_BUILD_EXE=0 UST_EXTENSION=1
    python:
    - 3.6
    install:
    - ".build/.travis/install-ubuntu.sh"
    script:
    - ".build/.travis/build-py36.sh"
    - ".build/.travis/release.sh"
    - python setup.py test
  - env: IMG="ubuntu1604" BUILD_TARGET="standalone" UST_BUILD_EXE=1 UST_EXTENSION=0
    python:
    - 3.6
    install:
    - ".build/.travis/install-ubuntu.sh"
    script:
    - ".build/.travis/build-py36.sh"
    - ".build/.travis/release.sh"
    - python setup.py test

  - env: OS="centos:7" IMG="centos7" SH="docker exec -t ${IMG} bash -c" BUILD_TARGET="pex"
    services:
    - docker
    python:
    - 3.6
    before_install:
    - chmod +x .build/.travis/*.sh
    - docker run -d --name ${IMG} -v $(pwd):/travis -w /travis -e IMG="${IMG}" -e
      TRAVIS_TAG="${TRAVIS_TAG}" -e BUILD_TARGET="${BUILD_TARGET}" -e UST_BUILD_EXE=0
      -e UST_EXTENSION=1 ${OS} tail -f /dev/null
    - docker ps 
    install:
    - "$SH .build/.travis/install-centos.sh"
    script:
    - "$SH .build/.travis/build-py36-centos.sh"
  - env: OS="centos:7" IMG="centos7" SH="docker exec -t ${IMG} bash -c" BUILD_TARGET="standalone"
    services:
    - docker
    python:
    - 3.6
    before_install:
    - chmod +x .build/.travis/*.sh
    - docker run -d --name ${IMG} -v $(pwd):/travis -w /travis -e IMG="${IMG}" -e
      TRAVIS_TAG="${TRAVIS_TAG}" -e BUILD_TARGET="${BUILD_TARGET}" -e UST_BUILD_EXE=1
      -e UST_EXTENSION=0 ${OS} tail -f /dev/null
    - docker ps
    install:
    - "$SH .build/.travis/install-centos.sh"
    script:
    - "$SH .build/.travis/build-py36-centos.sh"

deploy:
  provider: releases
  api_key:
    secure: ADMCpxzAdUcA2P6woAnt4o6EoL6JPwH3885PYVsQIZIfA+IrEMEA8URDh6RDeMoNzdAtVfeYFx3e3QBtKS+JVfysj8GxjX4PkzcythAovTUjkximym4FhdWF76xLdyNvSN5NP5pEu4pnLGItVz16thGoTcvDGmTsEHZ6VoV7YGoVNqcMIbBMXAogyM6rEHcZ0f1yS6oYpJ4drhB4kJy9b1432Vz6Zq8sUwBJniPdec98RO2BhMJaMeWGOmdQlvOpdYmF3fH0P7LFPceE5XKR2RqjvtoeOzF1FQosAtATUlZaUfofqMJ7NtccbGkaFLY2qxpgv+hrQATN7YiZqEqQ+Mj0tCq9w/UOlVfBcKWUeBTZ7Hyk3OGllQ3JzVuGXu/oNCWCCtFjTSLnOuyGkY+8qEVXKdo5M+OYfc8Z5EMPOOUyEH+MNgYdC6Wpi1fo0lkpVYvfJPl/2TNbCF+6sIug7qICXOxnNB5fgHOChQU6jc/Wt2/MOrhrjvTpUwaDhhCENRkqxUMFZxsvqNDs9vneXQj0WVcnUGz3QeTImGJgyqHWxuPWrzQenG5fY5sihl44FAsqQZC46j4mQiIcsW8C0SURbBrPFOpvbq1qhyW/NuzC/qLwfvAwH9SLPvyKI9L5xFFgh3VAAyc05mrbav71qOvK7PKQW9pyoZ5qO51cNu8=
  file: release/*.*
  file_glob: true
  skip_cleanup: true
  draft: true
  on:
    repo: sdhau/user-sync.py
    all_branches: true
    tags: true
